package com.honemen.lanfang.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.honemen.lanfang.database.HttpRetryGetParam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HTTP_RETRY_GET_PARAM.
*/
public class HttpRetryGetParamDao extends AbstractDao<HttpRetryGetParam, Long> {

    public static final String TABLENAME = "HTTP_RETRY_GET_PARAM";

    /**
     * Properties of entity HttpRetryGetParam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Value = new Property(2, String.class, "value", false, "VALUE");
        public final static Property RequestId = new Property(3, long.class, "requestId", false, "REQUEST_ID");
    };

    private DaoSession daoSession;

    private Query<HttpRetryGetParam> httpRetryRequest_GetParamsQuery;

    public HttpRetryGetParamDao(DaoConfig config) {
        super(config);
    }
    
    public HttpRetryGetParamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HTTP_RETRY_GET_PARAM' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'KEY' TEXT NOT NULL ," + // 1: key
                "'VALUE' TEXT NOT NULL ," + // 2: value
                "'REQUEST_ID' INTEGER NOT NULL );"); // 3: requestId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HTTP_RETRY_GET_PARAM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HttpRetryGetParam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getKey());
        stmt.bindString(3, entity.getValue());
        stmt.bindLong(4, entity.getRequestId());
    }

    @Override
    protected void attachEntity(HttpRetryGetParam entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HttpRetryGetParam readEntity(Cursor cursor, int offset) {
        HttpRetryGetParam entity = new HttpRetryGetParam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // key
            cursor.getString(offset + 2), // value
            cursor.getLong(offset + 3) // requestId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HttpRetryGetParam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getString(offset + 1));
        entity.setValue(cursor.getString(offset + 2));
        entity.setRequestId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HttpRetryGetParam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HttpRetryGetParam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "getParams" to-many relationship of HttpRetryRequest. */
    public List<HttpRetryGetParam> _queryHttpRetryRequest_GetParams(long requestId) {
        synchronized (this) {
            if (httpRetryRequest_GetParamsQuery == null) {
                QueryBuilder<HttpRetryGetParam> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RequestId.eq(null));
                httpRetryRequest_GetParamsQuery = queryBuilder.build();
            }
        }
        Query<HttpRetryGetParam> query = httpRetryRequest_GetParamsQuery.forCurrentThread();
        query.setParameter(0, requestId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getHttpRetryRequestDao().getAllColumns());
            builder.append(" FROM HTTP_RETRY_GET_PARAM T");
            builder.append(" LEFT JOIN HTTP_RETRY_REQUEST T0 ON T.'REQUEST_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected HttpRetryGetParam loadCurrentDeep(Cursor cursor, boolean lock) {
        HttpRetryGetParam entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        HttpRetryRequest httpRetryRequest = loadCurrentOther(daoSession.getHttpRetryRequestDao(), cursor, offset);
         if(httpRetryRequest != null) {
            entity.setHttpRetryRequest(httpRetryRequest);
        }

        return entity;    
    }

    public HttpRetryGetParam loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<HttpRetryGetParam> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<HttpRetryGetParam> list = new ArrayList<HttpRetryGetParam>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<HttpRetryGetParam> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<HttpRetryGetParam> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
