package com.honemen.lanfang.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.honemen.lanfang.database.HttpRetryPostParam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HTTP_RETRY_POST_PARAM.
*/
public class HttpRetryPostParamDao extends AbstractDao<HttpRetryPostParam, Long> {

    public static final String TABLENAME = "HTTP_RETRY_POST_PARAM";

    /**
     * Properties of entity HttpRetryPostParam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Value = new Property(2, String.class, "value", false, "VALUE");
        public final static Property IsFile = new Property(3, boolean.class, "isFile", false, "IS_FILE");
        public final static Property RequestId = new Property(4, long.class, "requestId", false, "REQUEST_ID");
    };

    private DaoSession daoSession;

    private Query<HttpRetryPostParam> httpRetryRequest_PostParamsQuery;

    public HttpRetryPostParamDao(DaoConfig config) {
        super(config);
    }
    
    public HttpRetryPostParamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HTTP_RETRY_POST_PARAM' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'KEY' TEXT NOT NULL ," + // 1: key
                "'VALUE' TEXT NOT NULL ," + // 2: value
                "'IS_FILE' INTEGER NOT NULL ," + // 3: isFile
                "'REQUEST_ID' INTEGER NOT NULL );"); // 4: requestId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HTTP_RETRY_POST_PARAM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HttpRetryPostParam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getKey());
        stmt.bindString(3, entity.getValue());
        stmt.bindLong(4, entity.getIsFile() ? 1l: 0l);
        stmt.bindLong(5, entity.getRequestId());
    }

    @Override
    protected void attachEntity(HttpRetryPostParam entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HttpRetryPostParam readEntity(Cursor cursor, int offset) {
        HttpRetryPostParam entity = new HttpRetryPostParam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // key
            cursor.getString(offset + 2), // value
            cursor.getShort(offset + 3) != 0, // isFile
            cursor.getLong(offset + 4) // requestId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HttpRetryPostParam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getString(offset + 1));
        entity.setValue(cursor.getString(offset + 2));
        entity.setIsFile(cursor.getShort(offset + 3) != 0);
        entity.setRequestId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HttpRetryPostParam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HttpRetryPostParam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "postParams" to-many relationship of HttpRetryRequest. */
    public List<HttpRetryPostParam> _queryHttpRetryRequest_PostParams(long requestId) {
        synchronized (this) {
            if (httpRetryRequest_PostParamsQuery == null) {
                QueryBuilder<HttpRetryPostParam> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RequestId.eq(null));
                httpRetryRequest_PostParamsQuery = queryBuilder.build();
            }
        }
        Query<HttpRetryPostParam> query = httpRetryRequest_PostParamsQuery.forCurrentThread();
        query.setParameter(0, requestId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getHttpRetryRequestDao().getAllColumns());
            builder.append(" FROM HTTP_RETRY_POST_PARAM T");
            builder.append(" LEFT JOIN HTTP_RETRY_REQUEST T0 ON T.'REQUEST_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected HttpRetryPostParam loadCurrentDeep(Cursor cursor, boolean lock) {
        HttpRetryPostParam entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        HttpRetryRequest httpRetryRequest = loadCurrentOther(daoSession.getHttpRetryRequestDao(), cursor, offset);
         if(httpRetryRequest != null) {
            entity.setHttpRetryRequest(httpRetryRequest);
        }

        return entity;    
    }

    public HttpRetryPostParam loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<HttpRetryPostParam> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<HttpRetryPostParam> list = new ArrayList<HttpRetryPostParam>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<HttpRetryPostParam> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<HttpRetryPostParam> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
